-- Production starter schema
create table if not exists riders (
 id text primary key,
 name text not null,
 mobile text,
 status text default 'Active',
 created_at timestamptz default now()
);
create table if not exists performance (
 id bigint generated by default as identity primary key,
 date date not null,
 rider_id text references riders(id),
 orders int default 0,
 completed int default 0,
 cancel int default 0,
 reject int default 0,
 online_hours numeric default 0,
 created_at timestamptz default now()
);
create table if not exists penalties (
 id bigint generated by default as identity primary key,
 date date not null,
 rider_id text references riders(id),
 amount numeric default 0,
 reason text,
 status text default 'Pending',
 created_at timestamptz default now()
);
create table if not exists documents (
 id bigint generated by default as identity primary key,
 rider_id text references riders(id),
 name text,
 file_name text,
 storage_path text,
 created_at timestamptz default now()
);
create table if not exists vehicles (
 id bigint generated by default as identity primary key,
 plate text not null,
 model text,
 rider_id text references riders(id),
 reg_expiry date,
 ins_expiry date,
 status text default 'Active',
 created_at timestamptz default now()
);
